# Practicing with Pandas

In this session you are going to apply some of the knowledge you (hopefully) acquired
in Lecture 3.

In each step of this notebook is required that you perform some action.


----
Import the necessary libraries

In [1]:
from pandas import DataFrame, Series
from io import StringIO 
import pandas as pd
import numpy as np
import os
import matplotlib as mpl
import matplotlib.pyplot as plt

from IPython.display import Image
IMG_PATH, DATA_PATH = "./img", "./data"


def describe(a):
    if type(a) is np.ndarray:
        print("data:\n{}\nshape:{}\ndtype:{}\ntype: {}".format(a, a.shape, a.dtype, type(a)))
    elif type(a) is pd.Series:
        print("data:\n{}\nshape:{}\ndtype:{}\nname:{}\nindex-name:{}\ntype:{}".format(a, a.shape, a.dtype, a.name, a.index.name, type(a)))
    elif type(a) is pd.DataFrame:
        print("data:\n{}\nshape:{}\ntype:{}".format(a, a.shape,type(a)))
    else:
        print("{}, type:{}".format(a, type(a)))


hrule = lambda x : "="*x
Hrule = lambda x,y: "="*(x//2)+y+"="*(x//2)
Data = lambda file : os.path.join(DATA_PATH, file)
Img  = lambda img : os.path.join(IMG_PATH, img)

---

Download the dataset at the given url

In [2]:
url = "https://raw.githubusercontent.com/acalio/Data-Mining-Course/master/Lecture%203/data/nba.csv"

In [3]:
df = pd.read_csv(Data('nba.csv'))
df.head()

,Unnamed: 0,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
0,0,1,Russell Westbrook,PG,28,34.6,10.2,24.0,425.00,2.5,...,1.6,0.4,5.4,2.3,31.6,OKC,81,34.6,46,26.50
1,1,2,James Harden,PG,27,36.4,8.3,18.9,0.44,3.2,...,1.5,0.5,5.7,2.7,29.1,HOU,81,36.4,54,26.50
2,2,3,Isaiah Thomas,PG,27,33.8,9.0,19.4,463.00,3.2,...,0.9,0.2,2.8,2.2,28.9,BOS,76,33.8,51,6.59
3,3,4,Anthony Davis,C,23,36.1,10.3,20.3,505.00,0.5,...,1.3,2.2,2.4,2.2,28.0,NO,75,36.1,31,22.12
4,4,6,DeMarcus Cousins,C,26,34.2,9.0,19.9,452.00,1.8,...,1.4,1.3,3.7,3.9,27.0,NO/SAC,72,34.2,30,16.96

Remove the nasty ``Unnamed: 0`` column.

In [6]:
#df = df.drop('Unnamed: 0', axis=1)
df.head()

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
0,1,Russell Westbrook,PG,28,34.6,10.2,24.0,425.00,2.5,7.2,...,1.6,0.4,5.4,2.3,31.6,OKC,81,34.6,46,26.50
1,2,James Harden,PG,27,36.4,8.3,18.9,0.44,3.2,9.3,...,1.5,0.5,5.7,2.7,29.1,HOU,81,36.4,54,26.50
2,3,Isaiah Thomas,PG,27,33.8,9.0,19.4,463.00,3.2,8.5,...,0.9,0.2,2.8,2.2,28.9,BOS,76,33.8,51,6.59
3,4,Anthony Davis,C,23,36.1,10.3,20.3,505.00,0.5,1.8,...,1.3,2.2,2.4,2.2,28.0,NO,75,36.1,31,22.12
4,6,DeMarcus Cousins,C,26,34.2,9.0,19.9,452.00,1.8,5.0,...,1.4,1.3,3.7,3.9,27.0,NO/SAC,72,34.2,30,16.96

---
What is the shape of the data-frame? Which are the dtypes of the columns?

In [8]:
df.shape

(344, 32)

Print the name of all the columns

In [9]:
df.columns

Index(['Rk', 'PLAYER', 'POSITION', 'AGE', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'POINTS', 'TEAM', 'GP',
       'MPG', 'W', 'SALARY_MILLIONS'],
      dtype='object')

Divide the DataFrame into tow dataframe. The first one must contain only the non-numerical columns while the second one must contains the numerical columns.

In [10]:
df1 = df.select_dtypes(np.number)
df1.head()

,Rk,AGE,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,AST,STL,BLK,TOV,PF,POINTS,GP,MPG,W,SALARY_MILLIONS
0,1,28,34.6,10.2,24.0,425.00,2.5,7.2,343.000,7.7,...,10.4,1.6,0.4,5.4,2.3,31.6,81,34.6,46,26.50
1,2,27,36.4,8.3,18.9,0.44,3.2,9.3,0.347,5.1,...,11.2,1.5,0.5,5.7,2.7,29.1,81,36.4,54,26.50
2,3,27,33.8,9.0,19.4,463.00,3.2,8.5,379.000,5.8,...,5.9,0.9,0.2,2.8,2.2,28.9,76,33.8,51,6.59
3,4,23,36.1,10.3,20.3,505.00,0.5,1.8,299.000,9.7,...,2.1,1.3,2.2,2.4,2.2,28.0,75,36.1,31,22.12
4,6,26,34.2,9.0,19.9,452.00,1.8,5.0,361.000,7.2,...,4.6,1.4,1.3,3.7,3.9,27.0,72,34.2,30,16.96

Check if the dataframe contains missing data

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 32 columns):
Rk                 344 non-null int64
PLAYER             344 non-null object
POSITION           344 non-null object
AGE                344 non-null int64
MP                 344 non-null float64
FG                 344 non-null float64
FGA                344 non-null float64
FG%                343 non-null float64
3P                 344 non-null float64
3PA                344 non-null float64
3P%                322 non-null float64
2P                 344 non-null float64
2PA                344 non-null float64
2P%                344 non-null float64
eFG%               344 non-null float64
FT                 344 non-null float64
FTA                344 non-null float64
FT%                339 non-null float64
ORB                344 non-null float64
DRB                344 non-null float64
TRB                344 non-null float64
AST                344 non-null float64
STL                344 non-null float64
BLK                344 non-null float64
TOV                344 non-null float64
PF                 344 non-null float64
POINTS             344 non-null float64
TEAM               344 non-null object
GP                 344 non-null int64
MPG                344 non-null float64
W                  344 non-null int64
SALARY_MILLIONS    344 non-null float64
dtypes: float64(25), int64(4), object(3)
memory usage: 86.1+ KB

Display summary statistics

In [12]:
df.describe()

,Rk,AGE,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,AST,STL,BLK,TOV,PF,POINTS,GP,MPG,W,SALARY_MILLIONS
count,344.000000,344.000000,344.000000,344.000000,344.000000,343.000000,344.000000,344.000000,322.000000,344.000000,...,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000
mean,219.508721,26.421512,21.431395,3.454942,7.670349,360.636755,0.859302,2.425000,209.610087,2.597965,...,2.055814,0.674128,0.414826,1.218605,1.778488,9.373547,57.718023,21.431686,28.712209,7.254971
std,138.231057,4.293150,8.934384,2.218089,4.677051,183.628882,0.781660,2.024129,172.597681,1.839594,...,1.889567,0.413404,0.420448,0.831032,0.710112,6.301494,22.759975,8.934489,14.775730,6.517266
min,1.000000,19.000000,2.200000,0.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,2.000000,2.200000,0.000000,0.030000
25%,100.750000,23.000000,14.875000,1.800000,4.200000,364.500000,0.200000,0.800000,0.356000,1.200000,...,0.800000,0.400000,0.100000,0.700000,1.300000,4.975000,41.750000,14.875000,18.000000,2.142500
50%,206.500000,26.000000,21.550000,3.000000,6.650000,424.000000,0.700000,2.150000,293.500000,2.100000,...,1.500000,0.600000,0.300000,1.000000,1.800000,7.900000,66.000000,21.550000,29.000000,4.840000
75%,330.500000,29.000000,29.025000,4.700000,10.400000,468.000000,1.400000,3.600000,361.750000,3.700000,...,2.600000,0.900000,0.500000,1.600000,2.300000,12.725000,76.000000,29.025000,39.000000,11.070000
max,484.000000,40.000000,37.800000,10.300000,24.000000,667.000000,4.100000,10.000000,515.000000,9.700000,...,11.200000,2.000000,2.600000,5.700000,3.900000,31.600000,82.000000,37.800000,66.000000,30.960000

Sort the dataframe in descending order wrt to the colun ``SALARY_MILLIONS``

In [13]:
df = df.sort_values('SALARY_MILLIONS', ascending=False)
df.head()

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
6,8,LeBron James,SF,32,37.8,9.9,18.2,0.548,1.7,4.6,...,1.2,0.6,4.1,1.8,26.4,CLE,74,37.8,51,30.96
67,78,Al Horford,C,30,32.3,5.6,11.8,473.000,1.3,3.6,...,0.8,1.3,1.7,2.0,14.0,BOS,68,32.3,46,26.54
25,29,Mike Conley,PG,29,33.2,6.7,14.6,0.460,2.5,6.1,...,1.3,0.3,2.3,1.8,20.5,MEM,69,33.2,35,26.54
0,1,Russell Westbrook,PG,28,34.6,10.2,24.0,425.000,2.5,7.2,...,1.6,0.4,5.4,2.3,31.6,OKC,81,34.6,46,26.50
1,2,James Harden,PG,27,36.4,8.3,18.9,0.440,3.2,9.3,...,1.5,0.5,5.7,2.7,29.1,HOU,81,36.4,54,26.50

Sort the dataframe in descending order wrt to the column ``SALARY_MILLIONS`` and ``AGE``.
The first one in descending order and the second one in ascending order.

In [16]:
df = df.sort_values(['SALARY_MILLIONS', 'AGE'], ascending=[False,True])
df.head()

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
6,8,LeBron James,SF,32,37.8,9.9,18.2,0.548,1.7,4.6,...,1.2,0.6,4.1,1.8,26.4,CLE,74,37.8,51,30.96
25,29,Mike Conley,PG,29,33.2,6.7,14.6,0.460,2.5,6.1,...,1.3,0.3,2.3,1.8,20.5,MEM,69,33.2,35,26.54
67,78,Al Horford,C,30,32.3,5.6,11.8,473.000,1.3,3.6,...,0.8,1.3,1.7,2.0,14.0,BOS,68,32.3,46,26.54
1,2,James Harden,PG,27,36.4,8.3,18.9,0.440,3.2,9.3,...,1.5,0.5,5.7,2.7,29.1,HOU,81,36.4,54,26.50
0,1,Russell Westbrook,PG,28,34.6,10.2,24.0,425.000,2.5,7.2,...,1.6,0.4,5.4,2.3,31.6,OKC,81,34.6,46,26.50

Give me the top-10 players with highest salary. 

I only need the ``PLAYER`` column

In [19]:
df = df.sort_values('SALARY_MILLIONS', ascending=False)
#df.head(10)['PLAYER']
df.iloc[:10, 1]

6          LeBron James
25          Mike Conley
67           Al Horford
1          James Harden
0     Russell Westbrook
10         Kevin Durant
64        Dirk Nowitzki
19      Carmelo Anthony
5        Damian Lillard
34          Dwyane Wade
Name: PLAYER, dtype: object

The list of all the different teams

In [20]:
df.TEAM.unique()

array(['CLE', 'MEM', 'BOS', 'HOU', 'OKC', 'GS', 'DAL', 'NY', 'POR', 'CHI',
       'ATL', 'LAC', 'WSH', 'NO', 'BKN', 'CHA', 'SA', 'IND', 'LAL', 'DET',
       'MIL', 'ORL', 'NO/SAC', 'UTAH', 'MIA', 'DEN', 'TOR', 'PHX', 'MIN',
       'SAC', 'MIL/CHA', 'ORL/TOR', 'PHI', 'CHI/OKC', 'ATL/PHI/OKC',
       'HOU/LAL', 'BKN/WSH', 'ATL/CLE', 'NY/WSH', 'DEN/CHA', 'DAL/PHI',
       'DEN/POR', 'DAL/BKN', 'CLE/DAL', 'HOU/MEM', 'GS/CHA', 'NO/MEM',
       'NY/PHI', 'NO/ORL'], dtype=object)

I want to be able to execute the following query:
```
df.loc['GS']
```
It has to return all the players in lex order

In [21]:
df.set_index('TEAM').loc['GS']

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,AST,STL,BLK,TOV,PF,POINTS,GP,MPG,W,SALARY_MILLIONS
TEAM,,,,,,,,,,,,,,,,,,,,,
GS,12,Kevin Durant,SF,28,33.4,8.9,16.5,537.0,1.9,5.0,...,4.8,1.1,1.6,2.2,1.9,25.1,62,33.4,51,26.50
GS,24,Klay Thompson,SG,26,34.0,8.3,17.6,468.0,3.4,8.3,...,2.1,0.8,0.5,1.6,1.8,22.3,78,34.0,66,16.66
GS,142,Draymond Green,PF,26,32.5,3.6,8.6,418.0,1.1,3.5,...,7.0,2.0,1.4,2.4,2.9,10.2,76,32.5,62,15.33
GS,10,Stephen Curry,PG,28,33.4,8.5,18.3,468.0,4.1,10.0,...,6.6,1.8,0.2,3.0,2.3,25.3,79,33.4,65,12.11
GS,215,Andre Iguodala,SF,33,26.3,2.9,5.5,528.0,0.8,2.3,...,3.4,1.0,0.5,0.8,1.3,7.6,76,26.3,64,11.13
GS,322,Shaun Livingston,PG,31,17.7,2.3,4.2,547.0,0.0,0.0,...,1.8,0.5,0.3,0.8,1.6,5.1,76,17.7,63,5.78
GS,280,JaVale McGee,C,29,9.6,2.7,4.1,652.0,0.0,0.0,...,0.2,0.2,0.9,0.5,1.4,6.1,77,9.6,62,1.40

I want to obtain a pandas Series with the name of a TEAM as index and the number of player
for that team as value.

In [26]:
df.groupby('TEAM').count()[['PLAYER']]

             PLAYER
TEAM
ATL              12
ATL/CLE           2
ATL/PHI/OKC       1
BKN              11
BKN/WSH           2
BOS              15
CHA              16
CHI              10
CHI/OKC           6
CLE               6
CLE/DAL           2
DAL               7
DAL/BKN           1
DAL/PHI           2
DEN              14
DEN/CHA           1
DEN/POR           2
DET              11
GS                7
GS/CHA            1
HOU               5
HOU/LAL           2
HOU/MEM           1
IND              10
LAC              10
LAL              10
MEM              12
MIA               9
MIL              11
MIL/CHA           2
MIN              14
NO                9
NO/MEM            1
NO/ORL            1
NO/SAC            4
NY               11
NY/PHI            1
NY/WSH            1
OKC               9
ORL               9
ORL/TOR           2
PHI               9
PHX              10
POR              10
SA               11
SAC              10
TOR              10
UTAH             12
WSH               9

Return all the rows with at least NaN

In [38]:
dfnull = df[df.isnull().any(axis=1)]
dfnull

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
226,285,Bismack Biyombo,C,24,22.1,2.2,4.2,528.000,0.0,0.0,...,0.3,1.1,1.2,2.5,6.0,ORL,81,22.1,29,17.00
234,301,Ian Mahinmi,C,30,17.9,2.1,3.6,586.000,0.0,0.0,...,1.1,0.8,1.1,2.9,5.6,WSH,31,17.9,19,15.94
314,431,Miles Plumlee,C,28,10.8,1.0,2.0,478.000,0.0,0.0,...,0.4,0.3,0.7,1.6,2.5,MIL/CHA,45,10.8,19,12.50
161,193,Tyson Chandler,C,34,27.6,3.3,4.9,0.671,0.0,0.0,...,0.7,0.5,1.4,2.7,8.4,PHX,47,27.6,15,12.42
302,418,Omer Asik,C,30,15.5,1.0,2.1,477.000,0.0,0.0,...,0.2,0.3,0.5,1.6,2.7,NO,31,15.5,12,9.90
326,454,Cole Aldrich,C,28,8.6,0.7,1.4,523.000,0.0,0.0,...,0.4,0.4,0.3,1.4,1.7,MIN,62,8.6,23,7.64
237,305,Boban Marjanovic,C,28,8.4,2.1,3.8,545.000,0.0,0.0,...,0.2,0.3,0.3,0.7,5.5,DET,35,8.4,16,7.00
275,359,Ed Davis,PF,27,17.2,1.6,3.1,528.000,0.0,0.0,...,0.3,0.5,0.8,3.0,4.3,POR,46,17.2,19,6.67
258,332,Aron Baynes,C,30,15.5,1.9,3.7,513.000,0.0,0.0,...,0.2,0.5,0.7,2.2,4.9,DET,75,15.5,34,6.50
267,344,Roy Hibbert,C,30,14.2,1.7,3.1,544.000,0.0,0.0,...,0.2,1.0,0.7,2.1,4.6,DEN/CHA,48,14.2,24,5.00
92,109,Jahlil Okafor,C,21,22.7,4.8,9.4,514.000,0.0,0.0,...,0.4,1.0,1.8,2.4,11.8,PHI,50,22.7,15,4.79
328,456,Jordan Hill,C,29,6.7,0.7,1.9,385.000,0.0,0.0,...,0.1,0.0,0.6,1.3,1.7,MIN,7,6.7,2,4.00
249,320,Dewayne Dedmon,C,27,17.5,2.1,3.4,622.000,0.0,0.0,...,0.5,0.8,0.8,2.4,5.1,SA,76,17.5,55,2.90
296,398,Jakob Poeltl,C,21,11.6,1.2,2.1,583.000,0.0,0.0,...,0.3,0.4,0.5,2.1,3.1,TOR,54,11.6,38,2.70
329,457,Bruno Caboclo,SF,21,4.4,0.7,1.8,375.000,0.2,0.7,...,0.2,0.1,0.2,0.4,1.6,TOR,9,4.4,8,1.59
184,225,David Lee,PF,33,18.7,3.1,5.3,0.590,0.0,0.0,...,0.4,0.5,1.0,1.6,7.3,SA,79,18.7,58,1.55
320,442,Rakeem Christmas,PF,25,7.6,0.7,1.5,442.000,0.0,0.0,...,0.1,0.2,0.3,1.3,2.0,IND,29,7.6,14,1.47
330,458,Deyonta Davis,C,20,6.6,0.7,1.3,511.000,0.0,0.0,...,0.1,0.5,0.2,1.1,1.6,MEM,36,6.6,23,1.37
336,466,Brice Johnson,PF,22,3.0,0.7,2.3,0.286,0.0,0.0,...,0.7,0.3,0.3,0.0,1.3,LAC,3,3.0,1,1.33
335,464,Diamond Stone,C,19,3.4,0.4,1.9,231.000,0.0,0.0,...,0.0,0.1,0.3,0.7,1.4,LAC,7,3.4,6,1.31
324,448,Marshall Plumlee,C,24,8.1,0.8,1.4,0.533,0.0,0.0,...,0.2,0.2,0.6,1.1,1.9,NY,21,8.1,6,1.31
331,458,Deyonta Davis,C,20,6.6,0.7,1.3,511.000,0.0,0.0,...,0.1,0.5,0.2,1.1,1.6,MEM,36,6.6,23,1.31
339,481,John Lucas III,PG,34,2.2,0.2,0.8,0.250,0.0,0.2,...,0.4,0.0,0.0,0.0,0.4,MIN,5,2.2,3,0.98
341,482,Giancarlo Magalli,SG,22,3.4,0.0,0.8,NaN,0.0,0.4,...,0.0,0.0,0.0,0.4,0.2,CHA,5,3.4,2,0.87
337,471,Mike Tobey,C,22,12.5,0.5,2.0,0.250,0.0,0.0,...,0.0,0.0,0.5,1.0,1.0,CHA,2,12.5,0,0.07
279,373,Anthony Brown,SF,24,14.5,1.6,4.5,0.360,0.6,2.5,...,0.5,0.1,0.5,1.4,3.9,NO/ORL,11,14.5,3,0.06

Think about wheter dropping these value seems to be a reasonable choice or not.

In [41]:
df = df.dropna(axis=0)
df

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
6,8,LeBron James,SF,32,37.8,9.9,18.2,0.548,1.7,4.6,...,1.2,0.6,4.1,1.8,26.4,CLE,74,37.8,51,30.96
25,29,Mike Conley,PG,29,33.2,6.7,14.6,0.460,2.5,6.1,...,1.3,0.3,2.3,1.8,20.5,MEM,69,33.2,35,26.54
67,78,Al Horford,C,30,32.3,5.6,11.8,473.000,1.3,3.6,...,0.8,1.3,1.7,2.0,14.0,BOS,68,32.3,46,26.54
1,2,James Harden,PG,27,36.4,8.3,18.9,0.440,3.2,9.3,...,1.5,0.5,5.7,2.7,29.1,HOU,81,36.4,54,26.50
0,1,Russell Westbrook,PG,28,34.6,10.2,24.0,425.000,2.5,7.2,...,1.6,0.4,5.4,2.3,31.6,OKC,81,34.6,46,26.50
10,12,Kevin Durant,SF,28,33.4,8.9,16.5,537.000,1.9,5.0,...,1.1,1.6,2.2,1.9,25.1,GS,62,33.4,51,26.50
64,74,Dirk Nowitzki,PF,38,26.4,5.5,12.6,0.437,1.5,3.9,...,0.6,0.7,0.9,2.1,14.2,DAL,54,26.4,23,25.00
19,22,Carmelo Anthony,SF,32,34.3,8.1,18.8,433.000,2.0,5.7,...,0.8,0.5,2.1,2.7,22.4,NY,74,34.3,29,24.56
5,7,Damian Lillard,PG,26,35.9,8.8,19.8,444.000,2.9,7.7,...,0.9,0.3,2.6,2.0,27.0,POR,75,35.9,38,24.33
34,39,Dwyane Wade,SG,35,29.9,6.9,15.9,434.000,0.8,2.4,...,1.4,0.7,2.3,1.9,18.3,CHI,60,29.9,29,23.20
76,88,Dwight Howard,C,31,29.7,5.2,8.3,633.000,0.0,0.0,...,0.9,1.2,2.3,2.7,13.5,ATL,74,29.7,37,23.18
37,42,Chris Paul,PG,31,31.5,6.1,12.9,476.000,2.0,5.0,...,2.0,0.1,2.4,2.4,18.1,LAC,61,31.5,43,22.87
16,18,Bradley Beal,SG,23,34.9,8.3,17.2,482.000,2.9,7.2,...,1.1,0.3,2.0,2.2,23.1,WSH,77,34.9,48,22.12
3,4,Anthony Davis,C,23,36.1,10.3,20.3,505.000,0.5,1.8,...,1.3,2.2,2.4,2.2,28.0,NO,75,36.1,31,22.12
220,275,Chandler Parsons,SF,28,19.9,2.2,6.5,338.000,0.7,2.7,...,0.6,0.1,0.7,1.5,6.2,MEM,34,19.9,18,22.12
39,44,Derrick Rose,PG,28,32.5,7.2,15.3,471.000,0.2,0.9,...,0.7,0.3,2.3,1.3,18.0,NY,64,32.5,26,21.32
31,36,Kevin Love,PF,28,31.4,6.2,14.5,0.427,2.4,6.5,...,0.9,0.4,2.0,2.1,19.0,CLE,60,31.4,40,21.17
26,30,Brook Lopez,C,28,29.6,7.4,15.6,474.000,1.8,5.2,...,0.5,1.7,2.5,2.6,20.5,BKN,75,29.6,20,21.17
30,34,Marc Gasol,C,32,34.2,7.2,15.7,459.000,1.4,3.6,...,0.9,1.3,2.2,2.3,19.5,MEM,74,34.2,40,21.17
54,61,Nicolas Batum,SG,28,34.0,5.1,12.7,403.000,1.8,5.3,...,1.1,0.4,2.5,1.4,15.1,CHA,77,34.0,35,20.87
41,47,LaMarcus Aldridge,PF,31,32.4,6.9,14.6,477.000,0.3,0.8,...,0.6,1.2,1.4,2.2,17.3,SA,72,32.4,52,20.58
23,27,Blake Griffin,PF,27,34.0,7.9,15.9,493.000,0.6,1.9,...,0.9,0.4,2.3,2.6,21.6,LAC,61,34.0,40,20.14
36,41,Paul Millsap,PF,31,34.0,6.2,14.1,442.000,1.1,3.5,...,1.3,0.9,2.3,2.7,18.1,ATL,69,34.0,40,20.07
75,86,Ryan Anderson,PF,28,29.4,4.5,10.7,418.000,2.8,7.0,...,0.4,0.2,0.8,2.0,13.6,HOU,72,29.4,50,18.74
110,129,Allen Crabbe,SG,24,28.5,3.8,8.2,468.000,1.7,3.8,...,0.7,0.3,0.8,2.2,10.7,POR,79,28.5,39,18.50
13,15,Paul George,SF,26,35.9,8.3,18.0,461.000,2.6,6.6,...,1.6,0.4,2.9,2.7,23.7,IND,75,35.9,39,18.31
178,214,Luol Deng,SF,31,26.5,2.9,7.6,387.000,0.9,2.9,...,0.9,0.4,0.8,1.1,7.6,LAL,56,26.5,18,18.00
9,11,Kyrie Irving,PG,24,35.1,9.3,19.7,473.000,2.5,6.1,...,1.2,0.3,2.5,2.2,25.2,CLE,72,35.1,47,17.64
7,9,Kawhi Leonard,SF,25,33.4,8.6,17.7,485.000,2.0,5.2,...,1.8,0.7,2.1,1.6,25.5,SA,74,33.4,54,17.64
12,14,Jimmy Butler,SF,27,37.0,7.5,16.5,455.000,1.2,3.3,...,1.9,0.4,2.1,1.5,23.9,CHI,76,37.0,40,17.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,186,Rondae Hollis-Jefferson,SF,22,22.6,3.0,6.9,434.000,0.2,0.9,...,1.1,0.6,1.5,2.3,8.7,BKN,78,22.6,19,1.40
137,163,Michael Beasley,PF,28,16.7,3.9,7.3,532.000,0.3,0.8,...,0.5,0.5,1.2,1.6,9.4,MIL,56,16.7,23,1.40
224,280,JaVale McGee,C,29,9.6,2.7,4.1,652.000,0.0,0.0,...,0.2,0.9,0.5,1.4,6.1,GS,77,9.6,62,1.40
157,188,Marreese Speights,C,29,15.7,3.0,6.7,445.000,1.3,3.4,...,0.3,0.5,0.8,2.8,8.7,LAC,82,15.7,51,1.40
210,262,Timothe Luwawu-Cabarrot,SF,21,17.2,2.1,5.2,402.000,0.7,2.3,...,0.5,0.1,1.1,2.2,6.4,PHI,69,17.2,23,1.39
322,444,Demetrius Jackson,PG,22,3.4,0.6,0.8,0.750,0.2,0.2,...,0.0,0.0,0.0,0.0,2.0,BOS,5,3.4,1,1.38
44,51,Nikola Jokic,C,21,27.9,6.8,11.7,578.000,0.6,1.9,...,0.8,0.8,2.3,2.9,16.7,DEN,73,27.9,37,1.36
319,440,Treveon Graham,SG,23,7.0,0.7,1.5,475.000,0.3,0.6,...,0.2,0.0,0.1,0.7,2.1,CHA,27,7.0,10,1.31
252,324,Wayne Selden,SG,22,16.9,1.8,4.1,431.000,0.5,2.0,...,0.4,0.1,0.9,1.3,5.1,NO/MEM,14,16.9,6,1.31
245,314,Chasson Randle,PG,23,11.5,1.5,3.8,408.000,0.6,1.8,...,0.3,0.1,0.7,1.5,5.3,NY/PHI,26,11.5,8,1.31
229,290,Andrew Harrison,PG,22,20.5,1.6,5.0,325.000,0.6,2.2,...,0.7,0.3,1.2,2.7,5.9,MEM,72,20.5,38,1.31
318,439,Jake Layman,SF,22,7.1,0.7,2.5,292.000,0.4,1.5,...,0.3,0.1,0.3,0.6,2.2,POR,35,7.1,16,1.31
310,424,Bryn Forbes,SG,23,7.9,1.0,2.8,364.000,0.5,1.5,...,0.0,0.0,0.3,0.6,2.6,SA,36,7.9,24,1.31
300,408,Fred VanVleet,PG,22,7.9,1.1,3.0,0.351,0.3,0.8,...,0.4,0.1,0.4,1.0,2.9,TOR,37,7.9,25,1.31
291,388,Dejounte Murray,PG,20,8.5,1.3,3.1,431.000,0.2,0.6,...,0.2,0.2,1.0,0.8,3.4,SA,38,8.5,29,1.31
254,327,Anthony Bennett,PF,23,11.5,1.7,4.0,413.000,0.6,2.1,...,0.2,0.1,0.5,0.8,5.0,BKN,23,11.5,3,1.02
265,342,Isaiah Canaan,SG,25,15.2,1.6,4.4,364.000,0.6,2.4,...,0.6,0.0,0.5,0.9,4.6,CHI,39,15.2,19,1.02
206,258,Marcus Thornton,SG,29,17.4,2.5,6.4,0.400,0.8,2.4,...,0.6,0.1,0.8,1.5,6.6,WSH,33,17.4,15,0.98
342,483,Massimo Giletti,SG,22,3.4,0.0,0.8,0.000,0.0,0.4,...,0.0,0.0,0.0,0.4,0.2,CHA,5,3.4,2,0.87
343,484,Massimo Giletti,SG,22,3.4,0.0,0.8,0.000,0.0,0.4,...,0.0,0.0,0.0,0.4,0.2,CHA,5,3.4,2,0.87
309,423,Christian Wood,PF,21,8.2,0.9,1.8,522.000,0.0,0.4,...,0.2,0.5,0.5,0.8,2.7,CHA,13,8.2,5,0.87
340,482,Aaron Harrison,SG,22,3.4,0.0,0.8,0.000,0.0,0.4,...,0.0,0.0,0.0,0.4,0.2,CHA,5,3.4,2,0.87
295,397,Maurice Ndour,PF,24,10.3,1.2,2.7,453.000,0.0,0.2,...,0.5,0.3,0.4,0.9,3.1,NY,32,10.3,10,0.54
217,271,Jonathan Gibson,PG,29,13.6,2.1,5.6,368.000,0.9,2.6,...,0.5,0.0,1.2,1.2,6.2,DAL,17,13.6,4,0.47
325,452,Lamar Patterson,SG,25,8.0,0.6,3.0,0.200,0.2,1.2,...,0.2,0.0,0.8,1.2,1.8,ATL,5,8.0,1,0.25
299,405,Andrew Bogut,C,32,21.6,1.4,3.0,469.000,0.0,0.0,...,0.5,0.9,1.6,3.2,2.9,CLE/DAL,27,21.6,8,0.24
263,339,Jarell Eddie,SF,25,12.4,1.2,3.8,316.000,0.8,3.2,...,0.2,0.0,0.2,0.2,4.8,PHX,5,12.4,0,0.06
338,475,Alonzo Gee,SF,29,6.8,0.2,1.1,214.000,0.0,0.2,...,0.4,0.1,0.3,1.1,0.8,DEN,13,6.8,4,0.06
298,400,Jarrett Jack,PG,33,16.5,1.0,1.5,667.000,0.0,0.5,...,1.0,0.0,1.5,2.0,3.0,NO,2,16.5,1,0.06
271,352,Pierre Jackson,PG,25,10.5,1.6,4.9,333.000,0.4,1.4,...,0.3,0.0,0.4,0.6,4.4,DAL,8,10.5,4,0.03

Get all the duplicated rows

In [50]:
df.iloc[df.duplicated().values, : ]

,Rk,PLAYER,POSITION,AGE,MP,FG,FGA,FG%,3P,3PA,...,STL,BLK,TOV,PF,POINTS,TEAM,GP,MPG,W,SALARY_MILLIONS
306,420,Marcelo Huertas,PG,33,10.3,1.1,3.0,368.0,0.2,0.8,...,0.4,0.1,0.8,0.7,2.7,LAL,23,10.3,5,1.5

Remove duplicated rows and keep the first occurence of the duplicated value.

Substitute each position with a number. 
In particular:
```
PG -> 1, C->5, SF->3 SG->2 PF->4 PF-C->5
```

Add a new column which contains the full name of each team.

Call the new column ``FULL_TEAM``. 

Example:
``
df['FULL_TEAM'] = Golden State Warriors if TEAM == GS, Chicaco Bulls if TEAM == CHI ....
``

Note that in the list of TEAMS some player actually played for two different teams in the same year.

I need you to replace whether you find ``Team1/Team2`` with ``Team1``.

Recompute the FULL_TEAM column

Starting from the Player Column, create two columns each containing the 
first and the last name of a player. Then drop the original Player Column

Discretize the the ``3P%`` column by quantile. 

I want 4 categories: ``(SHARP_SHOOTER > SHOOTER > BLIND_AS_A_BAT > BETTER_GET_CLOSER)``

Let's check the number of element inside each bin

Encode the previous column as a one-hot-ecoding vector.
Replace the new vector with the the original column.

Create a new data frame (call it df1) which contains only the columns ``TEAM, SALARY_MILLIONS, POSITION``.

Then define a MultiIndex object (TEAM, POSITION) sorted in ascending order wrt the POSITION.

---
Let's load another dataset

Merge the two dataset on the TEAM column (call it dfmerged)

Extend the dfteam dataframe with the following information:

1. number of player per team
2. total amoun of salary
3. the name of the player with the hihest salary (see idxmax function)
4. the gap between the richest and the poorest player in the same team
5. the name of the richest and the poorest player in two separate columns
6. the total amount of point per game considering every player in the team
7. the name of the youngest player for every team

In [ ]:
# enjoy

---
Plotting
---

Take a fist look at the entire dataset.

Hint: scatter_matrix (it takes too long please plot subset of points and columns)

Ok, this matrix is too big. Now I ask you to make a stretch of the imagination.

Imagine you are asked to predict the Salary of a player. 

> Which are the most reasonable features to consider?

You lack of apriori knowledge? It's fine let'se the 
the [Pearson's correlation coefficient](https://it.wikipedia.org/wiki/Indice_di_correlazione_di_Pearson).

Select the features that are more significant for you and plot the scatter matrix.

Take a look to the Salary distribution per ``POSITION``. 

You should take a kind of plot that enables you to check also the presence of outliers.

Plot the histogram against the ``POINTS`` feature (use qcut).

The height of the bar must denote the nmber of player within the given a range of points.

Plot the density estimate of the ``SALARY_MILLIONS`` feature.

You have to plot the distribution separately for ``TEAM`` in a different subplot.

I want to understand how ``POINTS`` relates with the ``AGE`` of a player.

Therefore the x-axis of your plot should be the ``AGE`` feature while the y-axis
should be the ``POINTS`` feature.

Also, I want to represent in the same plot the position of each player, his team 
and his salary.

Finally, upon each point I want to see the last name of the player. (Hint: [axes annotation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.annotate.html))